#!/bin/bash

nvcc -O2 -DSINGLE -DCUSP -o poissonCUSPs poissonSolver.cpp CUSPsolver.cu

nvcc -O2 -arch=sm_13 -DCUSP -o poissonCUSPd poissonSolver.cpp CUSPsolver.cu

nvcc -O2 -DSINGLE -DCUSPARSE -o poissonCUSPARSEs poissonSolver.cpp CUSPARSEsolver.cu -I$CULASPARSE_INC_PATH -lcublas -lcusparse

nvcc -O2 -arch=sm_13 -DCUSPARSE -o poissonCUSPARSEd poissonSolver.cpp CUSPARSEsolver.cu -I$CULASPARSE_INC_PATH -lcublas -lcusparse

nvcc -O2 -arch=sm_13 -DCULA -o poissonCULA poissonSolver.cpp CULAsolver.cu -L$CULASPARSE_LIB_PATH_64 -I$CULASPARSE_INC_PATH -lcula_core -lcula_sparse -lcolamd -lcublas -lcudart -lcusparse

icc -O2 -DMKLCG -mkl=sequential -o poissonMKLCG poissonSolver.cpp MKLCGsolver.cpp


